### ISSUE TITLE
EPIC 1

### ISSUE THREAD

**Issue by Harmonica-Men** [Harmonica-Men/simple-blog#1]
**Description:** Set up Django Project into GitPod Workspaces and deploy initial project to Heroku.
**Details:**

- [x] [USER STORY:](https://github.com/Harmonica-Men/simple-blog/issues/2) Set up GiHub repository
- [x]  [USER STORY:](https://github.com/users/Harmonica-Men/projects/6/views/1?pane=issue&itemId=70061713) Create a working Django app
- [x] [USER STORY: ](https://github.com/users/Harmonica-Men/projects/6/views/1?pane=issue&itemId=70061779)Deploy to Heroku
- [ ] USER STORY: Set up the IDE workspace on GitPod
