### ISSUE TITLE
USER STORY : Set up GitHub Repository

### ISSUE THREAD

**Issue by Harmonica-Men** [Harmonica-Men/simple-blog#2]
As a **developer**, I can **set up a repository on the GitHub platform** so that **I have control over the project versions.**

**Acceptance Criteria:**

I am working on the GitHub repository.

**Tasks:**

 - [x] Create new repository from template Code Institute - PP4 - AstroBlog 
 - [x] Create a project for the same repository
 - [x] Create labels for importance (Must, Should, Could, Won't Have)
 - [x] Create labels for Story Points
 - [ ] Create Epic's
 - [ ] Create User Stories

**Epic:**
[EPIC 1](https://github.com/Harmonica-Men/simple-blog/issues/1)
