### ISSUE TITLE
USER STORY: Create a working Django app

### ISSUE THREAD

**Issue by Harmonica-Men** [Harmonica-Men/simple-blog#3]
As a **Developer**, I need **to install all dependencies, correctly set settings.py and create working app** in **local environment.**

Acceptance Criteria :

All dependencies are installed, settings.py all set for local view and when project is ran locally, symbol of correctly set app is shown (rocket). 

**Tasks :**
  - [x] Install Django (minimum or greater 4.2.1)
  - [x] Create first app called "blogger"
  - [x] Set-up urls.py
  - [x] Set-up settings.py 

Epic :
[EPIC 1](https://github.com/Harmonica-Men/simple-blog/issues/1)
